### ISSUE TITLE
Android 9: Allow booster libraries to act upon screen on/off events

### ISSUE THREAD

**Issue by fredldotme** [ubports/platform-api#12]
This allows more advanced ports to do fancy stuff like limit the number of online CPUs dynamically based on the screen state.

Fixed by: https://github.com/ubports/platform-api/pull/11

**Comment by Flohack74** [comment]
Any instructions for testers?

**Comment by fredldotme** [comment]
> Any instructions for testers?

On the Pixel 3a testers can run these commands and see if their CPU count limits change based on screen on/off state:

```
cat /sys/devices/system/cpu/cpuquiet/nr_min_cpus
cat /sys/devices/system/cpu/cpuquiet/nr_max_cpus
```

**Comment by cibersheep** [comment]
Pixel 3a on last dev

Screen on
```
nr_min_cpus 2
nr_max_cpus 8
```

Screen off
```
nr_max_cpus 2
nr_min_cpus 2
```
